# Generated by Django 5.2.17 on 2026-09-03 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifier_app', '0002_document_classification_result_document_ocr_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'permissions': [('can_view_dashboard', 'Can view dashboard')]},
        ),
    ]
