# Generated by Django 5.2.17 on 2026-09-03 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifier_app', '0003_alter_document_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'permissions': [('can_view_dashboard', 'Can view dashboard'), ('run_ocr', 'Can run OCR'), ('classify_document', 'Can classify document')]},
        ),
    ]
