# Generated by Django 5.2.17 on 2026-09-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier_app', '0006_manualindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_type', models.CharField(max_length=50)),
                ('progress', models.IntegerField(default=0)),
                ('loss', models.FloatField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
