# Generated by Django 5.2.17 on 2026-09-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier_app', '0009_trainingdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingdomain',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
