# Generated by Django 5.2.17 on 2026-09-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier_app', '0012_document_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingdomain',
            name='created_by',
        ),
        migrations.AddField(
            model_name='trainingdomain',
            name='is_trained',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trainingdomain',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
