# Generated by Django 5.2.17 on 2026-09-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier_app', '0015_humanindex_min_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingdocument',
            name='vector_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
