# Generated by Django 5.2.17 on 2026-09-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier_app', '0016_trainingdocument_vector_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='combined_embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
