# Generated by Django 5.2.17 on 2026-09-04 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier_app', '0004_alter_document_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='classifier_app.document')),
            ],
        ),
    ]
