# Generated by Django 5.2.17 on 2026-09-06 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier_app', '0008_humanindexcategory_trainingdomain_humanindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200)),
                ('file_path', models.CharField(max_length=500)),
                ('ocr_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifier_app.trainingdomain')),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifier_app.humanindex')),
            ],
        ),
    ]
