# Generated by Django 5.2.17 on 2026-09-06 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier_app', '0010_trainingdomain_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='dossier_type',
        ),
        migrations.RemoveField(
            model_name='document',
            name='well',
        ),
        migrations.AddField(
            model_name='document',
            name='doc_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classifier_app.trainingdomain'),
        ),
        migrations.AddField(
            model_name='document',
            name='record_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='classification_result',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='classification_status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='ocr_status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
