# Generated by Django 5.2.17 on 2026-09-06 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier_app', '0011_remove_document_dossier_type_remove_document_well_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='index',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classifier_app.humanindex'),
        ),
    ]
