# Generated by Django 5.2.17 on 2026-09-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier_app', '0014_trainingdocument_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='humanindex',
            name='min_required',
            field=models.IntegerField(default=0),
        ),
    ]
